# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: cimg/ruby:3.1.2
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run: ruby --version
      - run: bundle install
      - run: bundle exec jekyll serve
      - persist_to_workspace:
        root: ./
        paths: _site

  deploy:
    machine:
      image: ubuntu-2004:current
    resource_class: medium
    steps:
       - attach_workspace:
        at: ./_site
       - add_ssh_keys:
          fingerprints:
            - "e5:63:5b:8f:3b:8d:bb:d1:70:7d:9f:2b:04:14:c5:10"
       - run:
            name: Deploy Over SSH
            command: |
              scp -r /var/www/mysite.com/_site circleci@148.100.79.41:/var/www/mysite.com/_site
       
# Invoke jobs via workflows ssh -o StrictHostKeyChecking=no circleci@148.100.79.41 "sudo touch /tmp/testing.txt"
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
    build-and-deploy:
      jobs:
          # - build
          - deploy